backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "work-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Create Date", name: "date", widget: "datetime" }
      - { label: Link, name: link, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Development,
              name: dev,
              widget: object,
              fields:
                [
                  { label: Sub-Headline, name: sub, widget: string },
                  { label: Heading, name: head, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Feature,
              name: feature,
              widget: list,
              fields:
                [
                  {
                    label: Card,
                    name: card,
                    widget: object,
                    fields:
                      [
                        { label: Icon, name: icon, widget: text },
                        { label: Title, name: title, widget: string },
                        { label: List, name: list, widget: list, field: {label: Text, name: text, widget: string }}
                      ],
                  },
                ],
            }
          - {
              label: IT,
              name: it,
              widget: object,
              fields:
                [
                  { label: Sub-Headline, name: sub, widget: string },
                  { label: Heading, name: head, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Sub-Headline, name: sub, widget: string },
                  { label: Heading, name: head, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Button, name: button, widget: string },
                ],
            }
      - file: "src/cms/layouts/site.md"
        label: "Site Settings"
        name: "site"
        fields:
          - {
            label: Social Media,
            name: sociallist,
            widget: list,
            fields:
              [
                {
                  label: Social,
                  name: social,
                  widget: object,
                  fields:
                    [
                      { label: Title, name: title, widget: string },
                      { label: Link, name: link, widget: string },
                      { label: Icon, name: icon, widget: text },
                    ],
                },
              ],
            }
         
 